### ISSUE TITLE
Missing "\n" in file-name output

### ISSUE THREAD

**Issue by xastarothx** [spalger/gulp-jshint-file-reporter#1]
Hey,

could you please add an '\n' in line 30 

if (i === 0) {
      // start off the output with the filename
      out.push('\n'+results.length + ' lint errors found in ' + result.file);
}

this will write the filename to the next line instead of appending it to the previous output. 

Thank you

**Comment by belgac** [comment]
I just created a pull request for this

**Comment by spalger** [comment]
Sorry, was on vacation for the last three weeks.
